### ISSUE TITLE
Rest day is not automatically applied

### ISSUE THREAD

**Issue by baocancode** [getmakerlog/web#215]
Hi,

I have one unused rest day, but it was not automatically applied on one day that I did not log anything (hardcore mode was off), hence my streak was broken.

Here is my account: https://getmakerlog.com/@baocancode

Regards.

**Comment by matteing** [comment]
Fixed.

On Aug 27, 2020, at 8:54 AM, Bao D <notifications@github.com<mailto:notifications@github.com>> wrote:

baocancode<https://getmakerlog.com/@baocancode>

**Comment by baocancode** [comment]
Cool, thanks :+1:
