### ISSUE TITLE
Unsub from blog not working

### ISSUE THREAD

**Issue by alinacsava** [getmakerlog/web#218]
I tried to unsubscribe, but it's not working. If I have an account at the blog, please delete it altogether.

<img width="1124" alt="Screenshot 2020-09-22 at 19 05 29" src="https://user-images.githubusercontent.com/5655500/94183960-86a05400-fea3-11ea-88e1-5449a662c702.png">

**Comment by matteing** [comment]
Try again now.

Sent from my iPad

On Sep 24, 2020, at 2:23 PM, Alina Sava <notifications@github.com> wrote:

﻿

I tried to unsubscribe, but it's not working. If I have an account at the blog, please delete it altogether.

[Screenshot 2020-09-22 at 19 05 29]<https://user-images.githubusercontent.com/5655500/94183960-86a05400-fea3-11ea-88e1-5449a662c702.png>

**Comment by alinacsava** [comment]
Done, thanks
