### ISSUE TITLE
Discussions cannot be praised, only replies

### ISSUE THREAD

**Issue by alinacsava** [getmakerlog/web#3]
On discussion page users can only praise replies, but not the original post itself
Example page: https://getmakerlog.com/discussions/archie-github-dynamic-readme-svgs

Neither the "started a thread" task can be praised.

![Uploading Screenshot 2020-07-31 at 09.26.00.png…]()

**Comment by matteing** [comment]
That's true, but it is by design. Although admittedly would be good to use it as part of some ranking algorithm.

Keeping open for design consideration for next versions.
